### ISSUE TITLE
博主你好，可以读取自己好友列表的微信号么

### ISSUE THREAD

**Issue by xiluo** [LTEnjoy/easyChat#1]

**Comment by LTEnjoy** [comment]
你好，是可以的。
我在ui_auto_wechat.py中实现了这个功能，你可以在class中找到这个函数find_all_contacts()。它能够读取你微信号中的所有好友并以列表的形式返回。
如果想要在图形界面中使用这个功能我暂时还没有实现，如果有需求的话后续可能会找时间完成这个功能。

**Comment by Hiro1012** [comment]
借楼请教下能否将获取的用户批量添加后群发呢？现在添加用户只能一个个加

**Comment by LTEnjoy** [comment]
> 
你好，这取决于你直接调用代码还是用图形界面。如果是调用代码的话能够很方便的实现你想要的功能，但如果是图形界面的话还涉及到的窗口的编写，可能会需要更久的时间。

**Comment by Hiro1012** [comment]
明白，谢谢！顺便提个小tips，我有看了下find_all_contacts()这个函数，会受到滚动条速度的影响，能获取大概200+个好友，如果好友较多，可以把间隔调小，我调成0.01了，获取1000+个好友没有问题

**Comment by LTEnjoy** [comment]
感谢你的反馈，经过测试调整为0.01后的确能够获得几乎全部的好友。
