### ISSUE TITLE
一点击发送，就卡住退出程序了

### ISSUE THREAD

**Issue by wangliandong** [LTEnjoy/easyChat#13]

**Comment by LTEnjoy** [comment]
你好，麻烦详细描述一下出错的内容以方便我定位问题所在。另外，可能的出错原因是在填写发送内容时没有按照规定的格式进行输入，请再检查一下这方面的问题。

**Comment by wangliandong** [comment]
![jietu](https://user-images.githubusercontent.com/10192776/231390438-d32ba841-5590-490c-b342-ac851b5a79f7.png)

**Comment by LTEnjoy** [comment]
你好，我不确定是不是系统本身兼容的问题，你的系统是不是win7的呢？我所有测试都是在win10系统上进行的。你可以尝试一下使用兼容模式运行程序。
![image](https://user-images.githubusercontent.com/52776915/231397614-430e373a-9ec3-4ca0-b960-f9e28365def4.png)
