### ISSUE TITLE
press_enter貌似会失灵

### ISSUE THREAD

**Issue by yoohooyoo** [LTEnjoy/easyChat#15]
尝试用最新版3.9.5.73微信，调用到press_enter失败了。
一直timeout。
但是用你给的gui.exe是可以的。
是我哪里用错了嘛。

**Comment by LTEnjoy** [comment]
你好，因为代码原理是获取界面的控件树来进行操作。显示timeout可能是当前你的窗口界面上没有打开微信所以搜索不到press_key()需要的控件。你可以看到press_key()都是在一些打开窗口的代码运行完之后再进行调用的，直接调用是可能出现问题的。

**Comment by yoohooyoo** [comment]
> 

开了呀。界面上前几步都成功了，比如打开微信，键入关键词搜索，打开页面，填入文字、图片。都成功了。
但是发送这一步没有成功。

**Comment by LTEnjoy** [comment]
你说用exe文件是可以的，那是通过代码调用的方式会报错吗？可以的话能看看你代码调用的方式以及报错信息吗？

**Comment by yoohooyoo** [comment]
是的，exe可以，代码不行。

报错信息如下：

发生异常: LookupError
Find Control Timeout(10s): {Depth: 15, Name: 'sendBtn', ControlType: ButtonControl}


ui_auto_wechat.py[22] click -> PermissionError: can't write the log!Find Control Timeout(10s): PermissionError: can't write the log!{PermissionError: can't write the log!DepthPermissionError: can't write the log!: PermissionError: can't write the log!15PermissionError: can't write the log!, PermissionError: can't write the log!NamePermissionError: can't write the log!: PermissionError: can't write the log!'sendBtn'PermissionError: can't write the log!, PermissionError: can't write the log!ControlTypePermissionError: can't write the log!: PermissionError: can't write the log!ButtonControlPermissionError: can't write the log!}

**Comment by LTEnjoy** [comment]
你好，我测试了一下，发现确实无法调用成功。通过检查我发现是因为微信版本更新导致的问题，现在已经将BUG修复，你可以下载新的py文件来使用。

**Comment by yoohooyoo** [comment]
> 

测试已经解决。点赞。
