### ISSUE TITLE
运行UI代码的时候貌似有问题

### ISSUE THREAD

**Issue by RelentZ** [LTEnjoy/easyChat#18]
您好，我运行您的exe文件程序正常，但是我想在运行的时候加一个姓氏的前缀，于是我运行您的wechat_gui.py，按照同样的方法，发现发送按钮没有点击响应。
我猜测或许是win32clipboard版本问题，您能提供一下当前您的pywin32的版本号么？
以及，如果可能的话，可否维护一个requirement.txt呢？
万分感谢您的支持！

**Comment by LTEnjoy** [comment]
![image](https://github.com/LTEnjoy/easyChat/assets/52776915/364cf206-a363-4974-9078-84fce6cab85d)
你好，这是我的环境的库，关于requirement.txt，我稍后会添加进去

**Comment by RelentZ** [comment]
万分感谢！
