### ISSUE TITLE
你好，请问可以实现复制群聊信息出来吗？

### ISSUE THREAD

**Issue by zysNLP** [LTEnjoy/easyChat#2]
如题

**Comment by LTEnjoy** [comment]
我稍微尝试了下，应该是可行的。不过release出来的话应该只有代码调用版本，不会为它做图形界面了。

**Comment by zysNLP** [comment]
好的，方便告知一下在哪里修改，怎么修改吗，感谢

**Comment by LTEnjoy** [comment]
这段时间我会抽空写出一个调用接口来，到时候会通知您。

**Comment by zysNLP** [comment]
好嘞，多谢

**Comment by LTEnjoy** [comment]
您好，我已经发布了新的功能出来，在README上有介绍，您可以在代码文件内部查看并调用。

**Comment by zysNLP** [comment]
可以在ui_auto_wechat.py的主函数执行__main__里增加一个代码调用版本上传文件的功能吗，比如定义一个path=/path/to/file，name=name1, 直接使用wechat.send_file(name, file)实现不了发送文件的功能。。

**Comment by LTEnjoy** [comment]
您好。经过测试我发现是代码本身出错导致的。现在已经将BUG修复，可以正常实现发送文件的功能。

**Comment by zysNLP** [comment]
好的，谢谢~

**Comment by LTEnjoy** [comment]
我没有用过inspect.exe这个软件，调试uiautomation我就是靠控制台输出去观察的。uiautomation我没有系统学过，就是看作者的github介绍然后摸索的。然后PyQt5教程好像很多，我只是为了做个界面临时学的，忘记得差不多了。。。有问题可以随时交流！

**Comment by zysNLP** [comment]
方便加下我的vx吗（18253177272），领导让我马上在另一个软件上用uiautomation开发功能出来，想请教下您一些具体类和函数的功能

**Comment by zysNLP** [comment]
想问下def get_contact函数这一行：search_box = auto.EditControl(Depth=8, Name="搜索")为什么是depth=8, name=搜索，这两个信息是从哪里测试得到的

**Comment by zysNLP** [comment]
好的，感谢！
