### ISSUE TITLE
群发功能方面，能否开发实现，通过加载excel文档来群发对应内容？

### ISSUE THREAD

**Issue by myhyday** [LTEnjoy/easyChat#21]
我的工作会涉及到大量一对一私聊通知
能帮忙开发一项功能，就是可以加载excel文档，根据excel文档的用户列，依次发送消息
根据内容列，实现不同用户发送的内容不一样

不知道是否能实现？

**Comment by LTEnjoy** [comment]
你好，加载excel文档的这个工作流会影响原本发送的逻辑，实现起来比较麻烦。一个替代方案是我让一条消息可以指定发送给若干用户。这样你可以先通过加载用户txt文件把所有用户导入，然后根据用户的编号设置对应的发送消息（例如第一条信息指定发送给第一个用户，第二条消息指定发送给第二个用户）。

**Comment by myhyday** [comment]
> 你好，加载excel文档的这个工作流会影响原本发送的逻辑，实现起来比较麻烦。一个替代方案是我让一条消息可以指定发送给若干用户。这样你可以先通过加载用户txt文件把所有用户导入，然后根据用户的编号设置对应的发送消息（例如第一条信息指定发送给第一个用户，第二条消息指定发送给第二个用户）。

我觉得也是可以的。其实也是跟txt导入用户类似，新增一个txt批量导入消息的功能。然后给对应编号的用户，发送对应编号的消息。

**Comment by LTEnjoy** [comment]
为了保证代码的可扩展性，我预计这样实现代码。对每一条消息msg，可以指定它需要发送给哪些用户，用编号来表示(例如1,2,5代表这条消息需要发送给编号为1，2，5的用户）。这要求用户在创建发送信息的txt文件时，需要在每一条消息中手动指明需要发送给哪些用户。

例子如下（example.txt）：
1,2,3:先生您好！
4,5,6:女士您好！

在这个例子中，冒号前面的数字代表词条消息要发送给哪些用户（前面的数字为编号，用英文逗号分开），而后面代表要发送的信息。

**Comment by LTEnjoy** [comment]
好的，我会尽快完成这个功能的实现，完成后会通知你的。

**Comment by LTEnjoy** [comment]
你好，新版的应用程序已经开发完成。你可以下载最新的exe文件并根据文档进行尝试。

**Comment by myhyday** [comment]
> 

辛苦大佬了，我学习试用一下哈~

**Comment by myhyday** [comment]
> 你好，新版的应用程序已经开发完成。你可以下载最新的exe文件并根据文档进行尝试。

您好，我试用了，还是挺好用的。
这里再请教您一个问题，就是在批量导入通知内容时候，针对于单条数据，是否可以增加换行符号？因为要发给对方的文本内容较长的话，如果没有换行，就感觉内容堆在一起，视觉上面不是太好。不知道是否能实现微信文本换行？

**Comment by LTEnjoy** [comment]
你好，我还是不推荐这种方式。因为换行符比较特殊，如果是从txt里加载的话，导致的结果是内容直接被切换到第二行里了，导致代码无法正确执行。我建议是如果内容太长的话，可以分两次发送，只需要两次发送的信息指向同一个用户就可以了。

**Comment by myhyday** [comment]
大佬周末好，我这边使用反馈一下使用建议：

在使用过程中，会出现闪退情况，目前遇到两种闪退请。

第一种是批量导入文本，没有设定每条文本应该发送给哪位人员，就是没有在文本前面加 1: 2: 这样的设定。导致程序闪退

第二种，我目前还没有找到原因，就是在程序运行批量群发时，第一名人员按照正常程序走完了，到了第二个人，就卡主不动，然后就闪退了。

建议增加一些节点规则校验，比如校验批量导入文档的内容，是否包含了1: 2:这样的信息，如果没有则运行阻断，并给出错误提示

**Comment by myhyday** [comment]
另外，请问是否可以增加运行中止的功能。

因为有一次在运行时，我发现信息发错人了（程序没有输入姓名直接发送了消息）

这个时候我想中止发送，却发现没有办法停止，只能强行关闭程序

**Comment by myhyday** [comment]
> 大佬周末好，我这边使用反馈一下使用建议：
> 
> 在使用过程中，会出现闪退情况，目前遇到两种闪退请。
> 
> 第一种是批量导入文本，没有设定每条文本应该发送给哪位人员，就是没有在文本前面加 1: 2: 这样的设定。导致程序闪退
> 
> 第二种，我目前还没有找到原因，就是在程序运行批量群发时，第一名人员按照正常程序走完了，到了第二个人，就卡主不动，然后就闪退了。
> 
> 建议增加一些节点规则校验，比如校验批量导入文档的内容，是否包含了1: 2:这样的信息，如果没有则运行阻断，并给出错误提示

今天又发生运行到一半，程序突然退出的情况，这次不是运行到第二人自动退出。具体为什么退出的原因并不清楚，我看了下数据，中断部分的内容很短，不至于说可能是内容超级长导致程序崩溃。

**Comment by LTEnjoy** [comment]
你好，能否将报错的txt文件发给我一份呢？然后是关于文本格式错误导致的闪退问题，我会加上一个检查机制，如果格式错误将返回提示。关于运行终止功能，我确实在调试的时候也遇到过这种情况，当时懒得处理，不过既然这种现象可能比较普遍，我也会考虑添加一个全局终止键来终止应用程序。

**Comment by LTEnjoy** [comment]
你好，最新版本已上传，请查看更新日志了解详细信息。

**Comment by myhyday** [comment]
> 你好，最新版本已上传，请查看更新日志了解详细信息。

好的，辛苦您了~

**Comment by myhyday** [comment]
![微信图片_20230725151419](https://github.com/LTEnjoy/easyChat/assets/137804274/10cb2f27-c362-4efe-a252-fc2143261db7)

运行到中途出现错误，提示“发送失败！请检查内容格式或是否有遗漏步骤！”。如图所示

**Comment by LTEnjoy** [comment]
麻烦定位一下具体是发送什么信息发给哪位用户时出现的错误。有可能是用户名字或者发送的内容出现了意想不到的问题导致发送失败。

**Comment by myhyday** [comment]
> 麻烦定位一下具体是发送什么信息发给哪位用户时出现的错误。有可能是用户名字或者发送的内容出现了意想不到的问题导致发送失败。

我开始也以为是名字或者内容有问题，所以我做实验，假设卡在B这里停止了。我就把B前面的人包括内容都删了，重新开始。发现B是可以正常发送出去的

不过我也还在尝试，因为的内容，是从excel直接粘贴到txt，然后txt导入的。而且通常会卡在第二个就发不出去，所以我在想，会不会是换行符有问题。等有空了，我再尝试一下

**Comment by LTEnjoy** [comment]
好的。如果是从excel直接粘贴的话，那可能是有问题的。因为excel粘贴过来可能会有一些特殊的符号导致程序无法识别。

**Comment by myhyday** [comment]
请问[Releases]里面的下载文件，为什么没有exe文件了呢？

**Comment by LTEnjoy** [comment]
因为随着版本的更新，每次我都要重新release最新的版本的exe文件，这样子比较麻烦。因此我现在直接将最新版的exe文件放在目录下，直接下载那个exe文件就可以了
