### ISSUE TITLE
获取聊天记录希望能增加图片获取功能

### ISSUE THREAD

**Issue by colordi** [LTEnjoy/easyChat#22]
我的使用场景是定时获取某一个群聊内的消息并储存到本地，现在一个问题就是图片无法获取，不知道大大能不能加上这个功能呢？

**Comment by LTEnjoy** [comment]
请问你存储到本地的形式是怎样的呢？目前获取的聊天记录都是文本形式，图片也是以[图片]的文本来存储的。如果要额外存储图片的话你要存在哪个地方呢？

**Comment by colordi** [comment]
我目前是把文本储存在txt中，如果可行的话，我想要图片也能保存在同目录下。非常感谢大大回答！

**Comment by LTEnjoy** [comment]
如果是这样存储的话，那图片可能只能作为文件存下来，而不能显示出在聊天记录里的顺序，这样没问题吗？

**Comment by colordi** [comment]
唔，我这里的使用场景没问题，不过这个也确实是一个问题，我也没想清楚该怎么处理，可能可以从图片保存时的名字入手？

**Comment by LTEnjoy** [comment]
![Uploading 1690010929206.png…]()
群聊的聊天记录里有图片项。如果需要保存图片的话，可以直接读取这里的图片进行保存，然后我在保存时的名字里加上序号代表图片发送的先后顺序这样。

**Comment by colordi** [comment]
OKOK。ヾ(≧∇≦谢谢≧∇≦)ノ

**Comment by LTEnjoy** [comment]
嗯嗯，我完成这个功能之后会通知你一声的

**Comment by colordi** [comment]
好嘞！

**Comment by LTEnjoy** [comment]
你好，我已经上传了存储图片的函数。你可以下载最新的文件进行查看和调用。有问题欢迎随时反馈！

**Comment by colordi** [comment]
哇，好的好的👌🏻
