### ISSUE TITLE
at:+人名，但是对方没有产生通知，就是普通的群消息，怎么办呢

### ISSUE THREAD

**Issue by ghostjum** [LTEnjoy/easyChat#23]
消息发了，但是对方没有产生通知，就是普通的群消息。

**Comment by LTEnjoy** [comment]
可以展示一下at后的信息发送内容框吗？如果格式没有问题的话，at展示的信息格式应该为1:at:人名

**Comment by ghostjum** [comment]
![1690853688246](https://github.com/LTEnjoy/easyChat/assets/44312696/09bd4260-26c3-455f-b278-a4197c924709)
![1690853665960](https://github.com/LTEnjoy/easyChat/assets/44312696/ba40aede-8e11-4328-8776-9f20fc4f8c59)

**Comment by ghostjum** [comment]
应该怎样输入呢

**Comment by LTEnjoy** [comment]
好的，我检查一下代码，确认无误后跟你反馈一下

**Comment by LTEnjoy** [comment]
你好，经过测试，at他人的代码中否存在一些问题，现在已经修改。你可以下载最新的exe文件进行尝试

**Comment by ghostjum** [comment]
好的，谢谢，我测试一下
