### ISSUE TITLE
有点疑惑

### ISSUE THREAD

**Issue by lclfy** [LTEnjoy/easyChat#24]
wechat_gui.py里面，“#获得用户编号列表” 这个for，在定时发送的时候，如果要发送的消息和用户编号不对（在“#判断是否需要发送给该用户”处）（例如消息发给2号，然后搜寻到1号了），这时候会跳出到raise，然后就不继续for循环了找下面的用户了，只能把raise改成continue，让目标用户不对的时候可以继续找下去直到正确的用户（好像一开始用还没问题，不知道啥情况）

**Comment by LTEnjoy** [comment]
你好，我也发现了。这个可能是我在做代码改动的时候不小心添上去了。现在已经改回来了。

**Comment by LTEnjoy** [comment]
你好，感谢你的反馈！我发现目前这些地方似乎其他用户还没有遇到相同的问题。如果之后其他用户也有反馈类似的情况，我会将其iuuuuuuuuuuuuu‘】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】】02
