### ISSUE TITLE
在我的电脑上需要管理员权限才能正常运行

### ISSUE THREAD

**Issue by NEPDream** [LTEnjoy/easyChat#25]
在我的电脑上，win10系统，打包好的exe文件，需要管理员权限才能正常运行。使用非管理员运行了，则会报错

**Comment by LTEnjoy** [comment]
你好，这应该是正常的。因为程序需要操控系统的鼠标以及键盘。

**Comment by NEPDream** [comment]
明白的，我的意思是，可以在readme里面说明一下，不然很多不知道的朋友可能就使用不成功了

________________________________

**Comment by LTEnjoy** [comment]
嗯可以的，我会把这个添加到注意事项里
