### ISSUE TITLE
什么时候完善自动回复的功能哦？

### ISSUE THREAD

**Issue by zhoul-sz** [LTEnjoy/easyChat#28]

**Comment by LTEnjoy** [comment]
自动回复的功能实现起来有点麻烦，而且只能通过代码的方式进行调用。我目前暂时还没有打算进行完善，等之后有时间的时候会考虑将它实现的。

**Comment by jamescurrykd** [comment]
自动回复打算是用定时判断的方式还是中断的方式实现呢

**Comment by LTEnjoy** [comment]
我觉得应该是设置一个循环，每隔一分钟触发一次，自动搜索所有新消息，然后判断是否需要自动回复。
