### ISSUE TITLE
是否可以增加默认微信exe地址功能

### ISSUE THREAD

**Issue by myhyday** [LTEnjoy/easyChat#29]
每次打开exe文件，都要手动选择微信可执行程序地址，比较麻烦
是否可以增加设置默认地址的功能，这样就只需要设置一次就可以了

**Comment by LTEnjoy** [comment]
如果是直接在代码层面改写的话会比较方便。但通过exe调用的话其实有点麻烦。一个可行的方法比如设置环境变量，然后程序自动读取对应的地址变量。但是这样子有点大动干戈的感觉。我个人推荐是把微信的地址复制到桌面上，然后直接选择桌面上的微信执行程序就可以了。
