### ISSUE TITLE
请教ui_auto_wechat.py里调用send_file()的问题

### ISSUE THREAD

**Issue by Hiro1012** [LTEnjoy/easyChat#3]
我尝试调用send_file()发送图片，发现剪切板是空的，无法发送空白消息
如果使用wechat_gui.exe操作是正常的
使用wechat_gui.py也会出现剪切板有图片，但发送的时候还没粘贴上因此无法发送空白消息的情况

**Comment by LTEnjoy** [comment]
你好，感谢你的反馈。
关于send_fiile()发送图片失败的问题，我之前调试过现在应该已经解决了。对于查看剪切板是空的情况，我看过虽然显示出来是空白的，但是能复制出图片。能请你详细描述一下问题的细节吗？

**Comment by Hiro1012** [comment]
之前我是在Mac用的虚拟机运行，刚试了直接用PC，问题又不存在了，估计还是虚拟机的问题
