### ISSUE TITLE
群发一千多人发现的问题

### ISSUE THREAD

**Issue by bubugamer** [LTEnjoy/easyChat#31]
群发多人功能（7.22的版本），发送的内容是“一段文字+一张图片”，运行过程中有下面几种异常的情况：1、没收到消息；2、只收到文字或图片；3、重复（2、3次）收到文字或/和图片

发消息期间我没碰过电脑，整天耗时还是比较长的，发了大半天吧（三个月前使用的，记不清细节了，今天突然想到上来提个issues……）

**Comment by LTEnjoy** [comment]
你好，这种情况比较复杂，因为涉及到的发送人数太多了，想要复现bug有点困难。。。如果后续还有相应的情况的话，可以尝试给出一些能复现问题的案例，然后我会分析修改一下。感谢你的反馈！
