### ISSUE TITLE
是基于视觉（截图分析）工作的吗？这样锁屏后无法用吧。。

### ISSUE THREAD

**Issue by mxdlzg** [LTEnjoy/easyChat#32]
包括关屏后，桌面停止渲染，截不到图片。

**Comment by LTEnjoy** [comment]
不是的，基于uiautomation做的。相当于程序自动操控鼠标和键盘。

**Comment by mxdlzg** [comment]
> 不是的，基于uiautomation做的。相当于程序自动操控鼠标和键盘。

貌似这库锁屏后也无法工作： https://github.com/yinkaisheng/Python-UIAutomation-for-Windows/issues/5#issuecomment-227929009

easyChat实测锁屏后也没执行消息发送

**Comment by LTEnjoy** [comment]
嗯，关于这一点可能确实是这样。不过如果需要定时操作的话，不锁屏应该也可以的吧。
