### ISSUE TITLE
get_contact 函数，如果好友昵称近似会出现的问题，见图

### ISSUE THREAD

**Issue by Wwj0811** [LTEnjoy/easyChat#38]
![image](https://github.com/LTEnjoy/easyChat/assets/24700133/4c7c8ef5-0242-4ead-b01d-d0b07361abeb)
这种情况下按回车键的话就会选择到机器人2里边，是错误的
是否考虑可以对比搜索结果，完全一致才可以点击到窗口

**Comment by LTEnjoy** [comment]
你好，感谢你的反馈。这种情况修改起来比较复杂，需要考虑更多的边界情况。我个人建议将联系人的名字稍作更改来方便区分。
