### ISSUE TITLE
建议不做ui，专注于封装成接口，这样可玩性高

### ISSUE THREAD

**Issue by zxjsir-hub** [LTEnjoy/easyChat#4]
感谢博主奉献代码，个人建议不做ui界面，虽然也可以自己改，个人感觉直接封装成库，大家调用接口更好些

**Comment by LTEnjoy** [comment]
您说的有道理，实现ui界面我本身也是现学现用，能够感受到扩展功能时的繁琐与无力。之所以会提供一个ui界面是希望能够给本身不会或不需要安装编译环境运行python文件的使用者提供一个简易的版本。在这之后我也会考虑将其封装成一个比较简易可扩展的库供代码开发者使用。

**Comment by zxjsir-hub** [comment]
出于这样考虑的话，也完全可以做成库，同时提供一个打包好exe程序（调用库，做着简单常用功能），供没有开发基础的人使用。做ui确实很累，可能比功能都费功夫。。。

**Comment by LTEnjoy** [comment]
嗯嗯。我会抽个时间梳理一下结构，然后把它封装成库作为接口调用。

**Comment by LiangGame** [comment]
现在有封装好的库吗

**Comment by LTEnjoy** [comment]
抱歉哈，一直没有花时间在封装库上，因为我感觉其实现在的功能还没有复杂到要专门调用库的情况。你可以直接下载ui_auto_wechat.py文件然后导入该文件来调用类，这样也很方便。
