### ISSUE TITLE
怎么知道微信客户端的界面结构

### ISSUE THREAD

**Issue by cyxxg** [LTEnjoy/easyChat#44]
我想试着优化一些细节，比如，当前聊天窗口如果已经是我想要的窗口，就不再进行搜索
也想着试着开发一下获取微信群聊中群成员信息（比如名字）的功能
但苦于不清楚微信的界面结构，实现起来很困难

**Comment by LTEnjoy** [comment]
你好,想要了解微信的界面结构,你可以通过automation.py文件来查看微信的组织形式:
![image](https://github.com/LTEnjoy/easyChat/assets/52776915/10b8ff88-58be-4235-9a4f-a885a3357d4a)
我在ui_auto_wechat文件里面列出了一些可用的控件:
![image](https://github.com/LTEnjoy/easyChat/assets/52776915/5b7d88d8-76b7-4dd7-8bc6-9b68888ae7ab)

你可以参考我的一些函数的实现例子来自定义操作.

**Comment by cyxxg** [comment]
> 你好,想要了解微信的界面结构,你可以通过运行automation.py文件来查看微信的组织形式: ![image](https://private-user-images.githubusercontent.com/52776915/328806907-10b8ff88-58be-4235-9a4f-a885a3357d4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTE5MDgsIm5iZiI6MTcxNTMxMTYwOCwicGF0aCI6Ii81Mjc3NjkxNS8zMjg4MDY5MDctMTBiOGZmODgtNThiZS00MjM1LTlhNGYtYTg4NWEzMzU3ZDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAzMjY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNTY1ZjRkMzgwY2Q2MzE5OGQ0NTM4MTMzODM3Y2I3NzQwZjE3NzYyNWY5MmFjOTE5NmVjZGM0NWI3ODUxZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.inqf6uzy4s6SO4lc1ZKhHJ6IH-F65yalxjrmd4BTpe0) 我在ui_auto_wechat文件里面列出了一些可用的控件: ![image](https://private-user-images.githubusercontent.com/52776915/328807135-5b7d88d8-76b7-4dd7-8bc6-9b68888ae7ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMTE5MDgsIm5iZiI6MTcxNTMxMTYwOCwicGF0aCI6Ii81Mjc3NjkxNS8zMjg4MDcxMzUtNWI3ZDg4ZDgtNzZiNy00ZGQ3LThiYzYtOWI2ODg4OGFlN2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDAzMjY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNjU0MzU5ODVlMGUxMGQ1YTQ1MzQ3NzQwZmU2YmQwOTEwODhkM2FjN2M2MzNhNDg0NzBiMjIyZjMzOWI2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cxfcm4s3-7Hcim6gNavfsYZN82c_6ytzSWWvCshRzd0)
> 
> 你可以参考我的一些函数的实现例子来自定义操作.

进入“测试”群界面之后上方的群名，这里的UI结构是不是不太对，我运行了以下代码：
![image](https://github.com/LTEnjoy/easyChat/assets/154854888/b0aaa64c-46be-4f43-a338-6d7c0608a108)
鼠标点击的却是左侧聊天列表的群
![image](https://github.com/LTEnjoy/easyChat/assets/154854888/fcd707ee-1045-4f36-8e98-b4f6845ed1e9)

**Comment by LTEnjoy** [comment]
你好，有可能是因为微信的版本更新导致界面控件改变了.我建议你重新运行一下automation.py文件,这个文件可以显示当前程序的层级结构.

**Comment by cyxxg** [comment]
好的，谢谢
