### ISSUE TITLE
定时发送信息设置了时间没有发送

### ISSUE THREAD

**Issue by K736882888** [LTEnjoy/easyChat#46]
操作步骤：添加时间——开始定时（内容/）

不定时可以正常使用不知道什么原因定时到时间有没有操作/发送

**Comment by Willshanyi** [comment]
原来是 有延迟大概十秒左右不定

**Comment by LTEnjoy** [comment]
由于程序逻辑原因是会有一定延迟的，如果后续还有问题欢迎继续提问。
