### ISSUE TITLE
如何批量导入定时发送文本内容？

### ISSUE THREAD

**Issue by TerryZT** [LTEnjoy/easyChat#47]
![1717550302308](https://github.com/LTEnjoy/easyChat/assets/89681010/6fa8c894-a309-430c-a738-bb64bf8b6d31)
按照日期每天发送一条文本内容，当天日期发生对应内容，早上 8:00 发送一次，下午 5:00 发送一次（内容一样）

**Comment by LTEnjoy** [comment]
你可以根据这个要求导入定时发送的文本内容：![image](https://github.com/LTEnjoy/easyChat/assets/52776915/9271cf70-8f80-47a0-88a4-bdd35b9f332a)

**Comment by swordspoet** [comment]
你好，当文本内容会定时变化的话，定时发送文本内容的功能是不是无法自动加载变化的内容？

**Comment by LTEnjoy** [comment]
你好，是的。当输入完文本内容后，发送的信息就固定了。

**Comment by swordspoet** [comment]
> 你好，是的。当输入完文本内容后，发送的信息就固定了。

谢谢，那我研究一下如果文本内容有了变动，定时发送的内容也跟着变动。
