### ISSUE TITLE
请问，有封号风险吗？

### ISSUE THREAD

**Issue by Yidk12** [LTEnjoy/easyChat#48]

**Comment by LTEnjoy** [comment]
你好，这个是没有封号风险的。因为整个程序并不是对微信进行了入侵，而是在模拟人定时操作鼠标和键盘打开微信发送消息。

**Comment by Yidk12** [comment]
jin，有办法批量获取通讯录名单吗？

**Comment by LTEnjoy** [comment]
我们提供了一个函数来自动获取通讯录名单：
![image](https://github.com/LTEnjoy/easyChat/assets/52776915/63dee164-0952-429b-8616-a666ea20a34e)

**Comment by Yidk12** [comment]
虽然我不会调试，但还是要谢谢你，UI界面没有看到可以自动获取的按钮，现在使用的是[easyChat_v20230724]这个版本，是公开的最新的，谢谢你了

**Comment by LTEnjoy** [comment]
你好，公开版本并不是最新的。请下载文件目录里的exe文件，这个版本一直是最新的
![image](https://github.com/LTEnjoy/easyChat/assets/52776915/98672553-1b41-4022-99ac-d4145c82163d)

**Comment by Yidk12** [comment]
![微信图片_20240627114334 - 副本](https://github.com/LTEnjoy/easyChat/assets/101029676/6ac4d1bd-6394-4807-9b05-b6bfa87e2f3d)
没有看到UI获取通讯录的界面哦

**Comment by LTEnjoy** [comment]
“保存微信好友列表”就是

**Comment by Yidk12** [comment]
已解决，感谢感谢
