### ISSUE TITLE
运行时闪退

### ISSUE THREAD

**Issue by Vincent-2018** [LTEnjoy/easyChat#5]
选择wechat.exe的运行路径，编辑好消息，点击发送按钮时，会卡顿一会，然后闪退。

环境 Win10

**Comment by LTEnjoy** [comment]
你好，请问可以把运行时出错的界面截图发上来看看吗？这样我能够确认是哪个地方出了问题。

**Comment by Vincent-2018** [comment]
1.打开界面
![image](https://user-images.githubusercontent.com/37291113/197339607-ee2e7a9a-1e13-4b46-b172-159c09ce2a98.png)
2.配置参数
![image](https://user-images.githubusercontent.com/37291113/197339656-3eed9bd8-5db5-4ed9-86fc-4725eaf063bd.png)

点击发送按钮
![image](https://user-images.githubusercontent.com/37291113/197339678-aa48bd7e-de9b-4158-ac77-05c9e65cb47c.png)

等待20s左右后，卡顿闪退

**Comment by LTEnjoy** [comment]
你好。经过测试，我这边似乎没有出现上述问题。请问是点击之后画面没有变化然后闪退吗？如果微信的弹窗没有出现，是否是wechat.exe文件无法正确执行？
