### ISSUE TITLE
求添加新功能

### ISSUE THREAD

**Issue by like2dog** [LTEnjoy/easyChat#50]
可以添加一些 群聊的功能吗

**Comment by LTEnjoy** [comment]
具体是什么可以描述一下吗？

**Comment by like2dog** [comment]
比如现在自动给好友发消息  可以扩展到给某个群聊发消息吗，比如 定时 某个周一10点 发消息给相亲相爱一家人 QAQ

**Comment by LTEnjoy** [comment]
这个功能已经支持了哦。可以翻看主页下面的示例。
