### ISSUE TITLE
可以导出微信通讯里的群名称吗？

### ISSUE THREAD

**Issue by lipan** [LTEnjoy/easyChat#52]

**Comment by lipan** [comment]
感谢作者的贡献！

**Comment by LTEnjoy** [comment]
你好，我检查了一下似乎是可行的。我有时间的时候会把这个功能加上去。

**Comment by LTEnjoy** [comment]
你好，我已经把这个功能按钮加上去了。你可以下载最新的exe文件进行尝试。

**Comment by lipan** [comment]
> 你好，我已经把这个功能按钮加上去了。你可以下载最新的exe文件进行尝试。

多谢作者，刚才下载试了，可以的
