### ISSUE TITLE
发送频率，能不能也加个输入框，可以控制间隔多少秒发一次就完美了

### ISSUE THREAD

**Issue by lipan** [LTEnjoy/easyChat#53]
感谢！！

**Comment by LTEnjoy** [comment]
可以描述得具体一些吗？在什么情况下控制发送的间隔呢？

**Comment by lipan** [comment]
> 可以描述得具体一些吗？在什么情况下控制发送的间隔呢？

给多个人发消息的时候，希望在发送前能停顿几秒。

**Comment by LTEnjoy** [comment]
可以的，我之后把他加上去

**Comment by lipan** [comment]
> 可以的，我之后把他加上去

好的，期待！

**Comment by LTEnjoy** [comment]
你好，我已经把这个功能加上去了。你可以下载尝试一下。

**Comment by lipan** [comment]
> 你好，我已经把这个功能加上去了。你可以下载尝试一下。

已经使用了，果然可以了，频率设置8s  不会影响微信发送状态，多谢大牛！
