### ISSUE TITLE
消息在发送过程中，能否支持暂停，之后再从当前的好友位置开始继续发送？

### ISSUE THREAD

**Issue by lipan** [LTEnjoy/easyChat#54]
今天再使用过程中，发现消息自动群发过程中，如果有人回复消息，想跟对方沟通一下，这个时候，就需要关掉软件。当再次打开软件时，还要从头开始群发动作。所以希望，能给个《暂停》按钮。发送过程中按一下暂停，就停止发送，可以进行一些操作。操作结束了，再取消暂停，消息继续从停止的位置开始继续往下发。

**Comment by lipan** [comment]
感谢！

**Comment by LTEnjoy** [comment]
这个实现起来比之前的要麻烦许多。而且这个的需求似乎不是那么大，因为完全可以群发完再回复消息吧。
