### ISSUE TITLE
代码调用，时不时报错，微信版本3.9.11.17

### ISSUE THREAD

**Issue by sanshuitmac** [LTEnjoy/easyChat#55]
报错信息：wx_ui_auto_wechat.py[30] click -> Find Control Timeout(10s): {Depth: 8, Name: '搜索', ControlType: EditControl}
请up帮忙查看下。。。

**Comment by LTEnjoy** [comment]
这种情况是程序无法找到微信的搜索框，这种问题能够稳定复现吗？
<img width="181" alt="1720420357510" src="https://github.com/LTEnjoy/easyChat/assets/52776915/b4309ce0-ffc6-4ced-9480-d74b07411ed1">

**Comment by sanshuitmac** [comment]
> 这种情况是程序无法找到微信的搜索框，这种问题能够稳定复现吗？ <img alt="1720420357510" width="181" src="https://private-user-images.githubusercontent.com/52776915/346452052-b4309ce0-ffc6-4ced-9480-d74b07411ed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjI5MjAsIm5iZiI6MTcyMDQyMjYyMCwicGF0aCI6Ii81Mjc3NjkxNS8zNDY0NTIwNTItYjQzMDljZTAtZmZjNi00Y2VkLTk0ODAtZDc0YjA3NDExZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA3MTAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NTQwMzQzMmU1ZDQ4MzI0ZWJlMjdlM2U1ZDg4MzNiODllZDk3MTQwMWI2YTY5ZjhiOTI4YTU3ZmUwZjQ0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Okzczhvdggda3q-GEHN8c8MAhw794gWdHFuRubK_HLk">

他是偶尔会这样报错，不定时出现。。。。刚才出现时，我看他是打开微信窗口，左上角也是有搜索框的，但就是提示找不到。

**Comment by LTEnjoy** [comment]
这个问题比较奇怪，因为我从来没遇到过这个问题，而且也不是能稳定出现的错误。建议再观察一下是否有什么出错的迹象。

**Comment by sanshuitmac** [comment]
我这挺经常发生。。我是使用ApsScheduler定时任务，每小时selenium打开浏览器截图，然后微信发送截图。我发现微信从最小化到获取窗口时，比较大概率报这个错，微信一直打开窗口就比较少。会不会是获取微信窗口后，马上寻找搜索框，间隔太短，导致找不到？我这出现也比较玄乎。我现在捕获这个异常，重试一次send_file，倒是每次重试时都能找到搜索框正常发送。

**Comment by LTEnjoy** [comment]
有可能有这个问题。我觉得可以人为加一个sleep函数，在寻找搜索框之前短暂等待一段时间，也许可以解决这个问题。

**Comment by sanshuitmac** [comment]
我在获取微信窗口后睡眠了几秒，再看看效果

**Comment by Davidyzb** [comment]
<img width="647" alt="微信图片_20240727213339" src="https://github.com/user-attachments/assets/c08d56a1-0d02-41d3-97b5-b976ebbdeee1">
up您好，我试用了参考#33的代码，没有成功实现自动回复功能，然后我在检查源代码的时候发现这个.chats没有被识别是什么原因呢
