### ISSUE TITLE
电脑上打开多个微信时，能不能选择某个微信进行群发

### ISSUE THREAD

**Issue by lipan** [LTEnjoy/easyChat#57]
同时登陆多个微信没法操作，只能退出留下一个发送。能不能切换微信进行群发

**Comment by LTEnjoy** [comment]
我没有尝试过多个微信的情况，这个似乎暂时解决不了。因为打开微信依靠的是用户首先设置一个微信的路径。现在有多个微信的情况下，除非有不同的路径对应打开不同的微信账号，否则程序没办法知道该选择哪个微信打开。
