### ISSUE TITLE
群发的过程中，如果遇到不存在的群，会导致程序自动停止

### ISSUE THREAD

**Issue by lipan** [LTEnjoy/easyChat#58]
发送的过程中，如果某个群被踢了，会发送失败，程序自动就停了。再发送的话，又要从第一个群开始发了。能否做个判断，发送失败，就继续发下一个。

**Comment by LTEnjoy** [comment]
如果发送失败，可以把前面都发过的用户都删除，然后从未发送的开始发送。这样可以解决问题吗？

**Comment by lipan** [comment]
> 如果发送失败，可以把前面都发过的用户都删除，然后从未发送的开始发送。这样可以解决问题吗？

群太多了，基本每次群发都要选几百个，手动删除还要找好久。

这个程序，能不能不通过搜索名字发送。通过点开通讯录，然后在通讯录李自上而下，点击每个人进行消息发送，是否可行，这样可以保证发送的人都是有效的好友或者有效的群

**Comment by LTEnjoy** [comment]
可以的，你可以在界面上找到保存所有联系人或者保存所有群组。然后你直接读取保存的文件就可以了。
