### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by SakuraXiaMF** [LTEnjoy/easyChat#6]
能否改成可以一口气添加多个用户的功能呀~
比如我输入 张三，李四，王五
直接就可以给
张三
李四
王五
而不需要我一个一个打进去……因为本地没有那些包……我不确定打包是否成功了

**Comment by LTEnjoy** [comment]
你好，相关的需求我已经实现并提交。请下载最新版本的exe进行尝试。

**Comment by SakuraXiaMF** [comment]
₍˄·͈༝·͈˄*₎◞ ̑̑谢谢



---- 回复的原邮件 ----
| 发件人 | Jin ***@***.***> |
| 日期 | 2022年11月03日 09:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [LTEnjoy/easyChat] 求教 (Issue #6) |

你好，相关的需求我已经实现并提交。请下载最新版本的exe进行尝试。
