### ISSUE TITLE
微信提示异常

### ISSUE THREAD

**Issue by jinhong101** [LTEnjoy/easyChat#60]
想问一下，问什么发送一会，微信就会提示说有异常，然后微信就会自动退出？

**Comment by LTEnjoy** [comment]
你好， 可以参考一下这个问题 https://github.com/LTEnjoy/easyChat/issues/53

**Comment by jinhong101** [comment]
感谢感谢，现在确实没问题了

**Comment by jinhong101** [comment]
> 你好， 可以参考一下这个问题 https://github.com/LTEnjoy/easyChat/issues/53

感谢感谢，现在没问题了
