### ISSUE TITLE
求一个新功能

### ISSUE THREAD

**Issue by 609293964** [LTEnjoy/easyChat#61]
试了下功能很赞
想看看能不能添加，某个时段随机发送文件的功能
例如：周一到周五晚上8~23点，随机时间发送文件夹内的内容给用户，然后发送完成后，删除已经发送过的文件（避免重复发送）
我试了添加文件，每次只能选择一个文件，文件很多需要一个个添加，能不能选择文件夹，识别文件夹内的所有文件

**Comment by LTEnjoy** [comment]
你这个功能太奇怪了。。。一次性添加文件夹的所有文件这个可以实现一下，但是前面所说的感觉没有什么人能够用到呀。

**Comment by 609293964** [comment]
> 这个功能太奇怪了。。。但是一次性添加文件夹的所有文件这个可以实现一下，前面说的感觉没有什么人能够使用呀。

因为夜班公司有考核TvT。。周一到周五晚上8~23点，发送1~3张图片到微信，这样我可以提前编辑好文件，随机时间发送到微信

**Comment by LTEnjoy** [comment]
如果只是这样的话，其实你可以随机设置时间然后发送的。在程序里随机挑选时间有点奇怪，改起来有点麻烦。

**Comment by Hallofanf** [comment]
请问能否添加repeat功能，我想要实现每天固定8点，12点，18点发送消息，就不用一口气设置一周的3个时间点

**Comment by LTEnjoy** [comment]
> 请问能否添加repeat功能，我想要实现每天固定8点，12点，18点发送消息，就不用一口气设置一周的3个时间点

你好，这个功能可以实现。我已经上传了最新版的exe文件，可以下载后根据提示使用。

**Comment by Hallofanf** [comment]
> > 请问能否添加repeat功能，我想要实现每天固定8点，12点，18点发送消息，就不用一口气设置一周的3个时间点
> 
> 你好，这个功能可以实现。我已经上传了最新版的exe文件，可以下载后根据提示使用。

谢谢，好高效啊

**Comment by LTEnjoy** [comment]
> #新功能建议 作者大大可以考虑下：发送的消息能不能是接龙消息，就是该消息是可以使别人参与接龙的？ 应用场景：一些运动场馆需要每天在微信群发送群接龙，这样球友会大概对人流量有个把握这样。

你好，如果说这种信息可以通过手动在聊天框输入出来，那么就可以通过该程序设置自动发送。否则的话需要专门处理了。关于接龙的信息如何发送我暂时还不太清楚。
