### ISSUE TITLE
[bug]似乎获取聊天记录无法获取红包消息

### ISSUE THREAD

**Issue by xieyumc** [LTEnjoy/easyChat#64]
<img width="596" alt="image" src="https://github.com/user-attachments/assets/544edaf2-a201-46ba-ad48-4046681e0ffc">
会显示无法识别该控件类型

**Comment by LTEnjoy** [comment]
获取聊天记录部分应该是添加了对红包信息的支持的。一个可能的原因是你这里收到红包的信息是用的英文所以程序没有检测到。你可以先把英文切换到中文再尝试一下。

**Comment by xieyumc** [comment]
感谢，
确实是英文的问题，虽然电脑的微信是中文，但是手机是英文，收到的红包消息也是英文了
我试了一下，判断语句改成            
`elif "红包" in list_item_control.Name or "Red packet" in list_item_control.Name:
`
就可以正常识别了，有没有考虑改进一下呢

**Comment by LTEnjoy** [comment]
嗯，我会把这个差异加入进去。之后会自动识别多个不同的关键词。
