### ISSUE TITLE
如何换行发送文本

### ISSUE THREAD

**Issue by Bigyayaya** [LTEnjoy/easyChat#68]
貌似没办法换行发送文本 读取txt文件里面的文本会被分成一行一条消息 如何才能把多行消息一次性发送出去![image](https://github.com/user-attachments/assets/ed2ead2d-1850-4281-acfe-6b335c9a7c2f)

**Comment by LTEnjoy** [comment]
你好我把这个功能加上了，现在可以输入``\n``来进行换行。你可以重新下载exe文件尝试。
