### ISSUE TITLE
为什么不使用pywinauto,而用Python-UIAutomation-for-Windows?

### ISSUE THREAD

**Issue by xiahan4956** [LTEnjoy/easyChat#69]
似乎pywinauto更加流行,好奇好奇,这样做的原因

**Comment by youzi-2333** [comment]
Don't download this file. This is a computer virus.

不要下载这个文件，这是一个计算机病毒。

**Comment by xiahan4956** [comment]
- - 还真是厉害啊..

**Comment by LTEnjoy** [comment]
你好，我没印象当时为什么选择这个库了。最开始我只是找了一个工具自娱自乐，后面发现可以解决实际问题之后就沿用之前的用法创建了这个仓库。

**Comment by LTEnjoy** [comment]
你好，我没印象当时为什么选择这个库了。最开始我只是找了一个工具自娱自乐，后面发现可以解决实际问题之后就沿用之前的用法创建了这个仓库。
