### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by HaoyuScut** [LTEnjoy/easyChat#7]
wechat_gui中
# 定时发送子线程类
class ClockThread(QThread):
    def __init__(self):
        super().__init__()
        # 是否正在定时
        self.time_counting = False
        # 发送信息的函数
        self.send_func = None
        # 定时列表
        self.clocks = None

    def __del__(self):
        self.wait()

    def run(self):
        while self.time_counting:
            localtime = time.localtime(time.time())
            hour = localtime.tm_hour % 24
            min = localtime.tm_min % 60

            for i in range(self.clocks.count()):
                **clock_hour, clock_min = self.clocks.item(i).text().split(" ")**//有误，三输入，应该为clock_hour, clock_min,content_times

                if int(clock_hour) == hour and int(clock_min) == min:
                    self.send_func()

            time.sleep(60)

**Comment by LTEnjoy** [comment]
你好，我检查了一下，你是正确的，感谢你的反馈！
根本原因是我在git push最新的版本时没有更新本地的代码文件，导致上传的代码其实是更久之前的版本因此出现了问题。现在已经将问题进行了修复。
如果程序还有什么问题欢迎随时提出issue！
