### ISSUE TITLE
定时发送功能 

### ISSUE THREAD

**Issue by INIMIG** [LTEnjoy/easyChat#72]
请问发送可以设定为每周的指定的天数发出吗? 例如: 总是每个星期二/四发出

**Comment by LTEnjoy** [comment]
你好，你可以查看星期二/四分别对应哪些日子，然后在定时的时候同时输入多个日期即可。
[cid:ed480282-53f0-4521-9334-e28b840bd782]
________________________________
发件人: INIMIG ***@***.***>
发送时间: 2024年10月11日 13:01
收件人: LTEnjoy/easyChat ***@***.***>
抄送: Subscribed ***@***.***>
主题: [LTEnjoy/easyChat] 定时发送功能 (Issue #72)


请问发送可以设定为每周的指定的天数发出吗? 例如: 总是每个星期二/四发出

―

**Comment by cc1217** [comment]
收到，我再学习一下，谢谢



---原始邮件---
发件人: "Jin ***@***.***&gt;
发送时间: 2024年10月11日(周五) 中午1:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [LTEnjoy/easyChat] 定时发送功能  (Issue #72)




 你好，你可以查看星期二/四分别对应哪些日子，然后在定时的时候同时输入多个日期即可。 
 [cid:ed480282-53f0-4521-9334-e28b840bd782] 
 ________________________________ 
 发件人: INIMIG ***@***.***&gt; 
 发送时间: 2024年10月11日 13:01 
 收件人: LTEnjoy/easyChat ***@***.***&gt; 
 抄送: Subscribed ***@***.***&gt; 
 主题: [LTEnjoy/easyChat] 定时发送功能 (Issue #72) 
 
 
 请问发送可以设定为每周的指定的天数发出吗? 例如: 总是每个星期二/四发出 
 
 ―
