### ISSUE TITLE
机器人发送消息异常

### ISSUE THREAD

**Issue by wc571498244** [LTEnjoy/easyChat#73]
<img width="610" alt="image" src="https://github.com/user-attachments/assets/5337d3bb-2658-4f56-b18b-84849feb63bc">
设置批量发送联系人，其中遇到被别人删除微信的，发送失败后；机器人暂停了，没有继续把联系人列表发送完。

**Comment by LTEnjoy** [comment]
你好，该问题现已修复。你可以下载最新exe文件进行尝试。

**Comment by wc571498244** [comment]
OK，感谢
