### ISSUE TITLE
保存微信好友列表 建议

### ISSUE THREAD

**Issue by wc571498244** [LTEnjoy/easyChat#74]
<img width="631" alt="image" src="https://github.com/user-attachments/assets/10be8bd7-64df-40c1-be3e-230151b3e802">
建议 导出好友列表 增加 "标签" 列

**Comment by LTEnjoy** [comment]
可以的，我之后有时间更新上去。

**Comment by LTEnjoy** [comment]
你好，我已经加入了导入标签列的功能，你可以下载最新版的exe进行尝试。
