### ISSUE TITLE
用户与内容整合

### ISSUE THREAD

**Issue by dzxwzw** [LTEnjoy/easyChat#75]
老师，您好，这个程序，很好用，可否将用户与内容整合在一起，就是我将用户与要发的内容一并写入TXT，我直接加载内容TXT，就可以发送，不用添加用户。用户与内容分离，我发现有时会将内容错发用户。谢谢！

**Comment by LTEnjoy** [comment]
你好，这个实现上比较复杂，我暂时不一定有时间去做这个。等我之后有空的时候可以思考一下。

**Comment by dzxwzw** [comment]
谢谢！

**Comment by LTEnjoy** [comment]
你好，我思考了一下。实现上还是用户和内容分离比较好。他们连在一起容易引起发送上的不方便。例如我有一条消息要发送过多个用户，还需要把所有用户的名字都加在同样的内容的前面。所以还是目前这个方式方便一些。
