### ISSUE TITLE
优化“加载内容txt文件”按钮功能的建议

### ISSUE THREAD

**Issue by dzxwzw** [LTEnjoy/easyChat#77]
老师，您好！
建议“加载内容txt文件”按钮功能，不自动加“text:”，由使用者自行在TXT文件中添加。这样使用者要发送“内容”时，TXT文件每行为“text:+用户序号:+具体内容”；要发送“文件”时，TXT文件每行为“file:+用户序号:+文件路径”。软件改动不大，望老师采纳。谢谢！

**Comment by dzxwzw** [comment]
建议“加载内容txt文件“的名称可改为”加载TXT文件发送（信息或文件）“；“添加文本内容”的名称可改为“添加要发送的信息”；“添加文件”的名称可改为“添加要发送的文件”。谢谢！

**Comment by dzxwzw** [comment]
![无标题](https://github.com/user-attachments/assets/e73ce586-3ca9-4afc-8f88-97c141250b95)
不好意思，觉得，第二建议有点啰嗦，此图觉得好些。

**Comment by dzxwzw** [comment]
![捕获](https://github.com/user-attachments/assets/3d3ee32e-2614-49e0-81d9-e170bcd1acac)
有点着相了。

**Comment by LTEnjoy** [comment]
你好，你的需求是想要在txt文件中允许发送文件信息吧。这个我之后可以考虑优化一下功能。不过后面的图形界面改动起来比较麻烦，在不影响使用的情况下我还是尽量保持原样。如果感兴趣的话你可以尝试实现一下然后提交PR，我可以把他合并进来~

**Comment by dzxwzw** [comment]
不好意思，我不懂，我只懂一点VFP编程。
