### ISSUE TITLE
请问是否支持 windows 7上面的旧版 Python 3.8.20 ?

### ISSUE THREAD

**Issue by bit-lang** [LTEnjoy/easyChat#78]

**Comment by LTEnjoy** [comment]
你好，python 3.8应该是支持的。你可以尝试一下看看具体情况是怎样。

**Comment by bit-lang** [comment]
> 你好，python 3.8应该是支持的。你可以尝试一下看看具体情况是怎样。

多谢你回复得好快
抱歉，没有写完就发出来了
还有是否支持 windows xp sp3 上的 python 3.4 ?

**Comment by LTEnjoy** [comment]
这个我就不太确定了。毕竟太老了，有可能连exe程序都没有办法运行起来。总而言之我觉得可以先试试。

**Comment by bit-lang** [comment]
多谢啦 我试试

**Comment by bit-lang** [comment]
> 你好，python 3.8应该是支持的。你可以尝试一下看看具体情况是怎样。

尝试运行 Python 
提示 import pyautogui error

pyautogui是需要单独安装的pip包吗

**Comment by LTEnjoy** [comment]
应该是，我把运行需要的库都列在requirement.txt里了，你可以用pip来安装。如果发现安装完之后还有缺少的库可以告诉我，我补充上去。

**Comment by bit-lang** [comment]
> 应该是，我把运行需要的库都列在requirement.txt里了，你可以用pip来安装。如果发现安装完之后还有缺少的库可以告诉我，我补充上去。

Win7 Python 3.8可以运行。
需要补充安装：
pyautogui, keyboard

**Comment by LTEnjoy** [comment]
好的，感谢测试！我们会把这两个库添加进去。
