### ISSUE TITLE
有新添加好友自动回复和自动添加备注功能吗

### ISSUE THREAD

**Issue by Kunye233** [LTEnjoy/easyChat#80]

**Comment by Kunye233** [comment]
如果可以按标签群发好友就更好了

**Comment by LTEnjoy** [comment]
你好，自动添加备注这个功能暂时无法做到。根据标签群发目前也没有实现，因为获取起来太麻烦了。不过我可以考虑在获取所有好友名称的同时将标签也自动获取了，到时候你根据获取的文件只留下对应标签的好友然后上传上去应该就可以了。

**Comment by LTEnjoy** [comment]
你好，我已经加入了导入标签的功能。你可以下载最新的exe文件进行尝试。
