### ISSUE TITLE
最新的微信强制退出问题

### ISSUE THREAD

**Issue by TallerCain** [LTEnjoy/easyChat#82]
尊敬的开发者，您好，
  我经过一段时间的使用，发现目前日然存在的问题就是：
当我设置为固定发送时间间隔为 10S，并且开启了防下线的开关，我使用22分钟后依然出现了强制下线的情况
我的想法：
能否将发送时间间隔设置为一个灵活的区间，比如说 **：自定义区间 8秒~20秒**（发送第一条消息后，间隔时间取自定义区间的随机值 ），等待发送第二条时，间隔时间为 随机数。不知道这样是否可以躲过微信的强制下线机制呢？求解答

**Comment by LTEnjoy** [comment]
我个人感觉是不是没有太大影响。目前不清楚微信下线的检测机制是什么。要不你试一下把间隔时间再调长一点看看还会不会强制下线呢？

**Comment by TallerCain** [comment]
收到，感谢您的回复

**Comment by hufengxiao** [comment]
> 收到，感谢您的回复

请问之后有还遇到强制下线的情况吗？您是如何设置新的间隔时间的？

**Comment by swordspoet** [comment]
把频率设置低一点。
