### ISSUE TITLE
设置定时发送消息闪退

### ISSUE THREAD

**Issue by BoboCactus** [LTEnjoy/easyChat#9]
普通的发送消息没有问题。定时发送消息时，添加时间没有问题，点击【开始定时】会立即闪退
![image](https://user-images.githubusercontent.com/33997216/225006546-1342bb3c-55cd-4e9f-ba1b-b1c27c68a235.png)
![image](https://user-images.githubusercontent.com/33997216/225007725-f26d9266-2aba-4c8f-9d3b-9923a021d230.png)
64 位操作系统, 基于 x64 的处理器，Windows 10 专业版

**Comment by LTEnjoy** [comment]
<img width="288" alt="微信截图_20230314210223" src="https://user-images.githubusercontent.com/52776915/225009289-876277d6-2757-4035-81e5-17e4f2f376d5.png">
你好，经过我的测试，这是由于你的时间格式填写有误导致的（参考图片中的格式）。为了保证代码的正常运行，请按照指定的格式填写定时时间。
如果还有什么问题，麻烦继续告知我一声噢~
